package entities

const DB_TABLE_IDM_USER = "idm_user"

type IdmUser struct {
	OrgId              string `gorm:"column:org_id;type:VARCHAR(64);primaryKey" json:"org_id,omitempty" yaml:"org_id,omitempty" field-id:"org_id" field-type:"varchar" field-comment:"企业ID"`                                               // 企业ID
	UserId             string `gorm:"column:user_id;type:VARCHAR(64);primaryKey" json:"user_id,omitempty" yaml:"user_id,omitempty" field-id:"user_id" field-type:"varchar" field-comment:"用户ID"`                                           // 用户ID
	UserName           string `gorm:"column:user_name;type:VARCHAR(64)" json:"user_name,omitempty" yaml:"user_name,omitempty" field-id:"user_name" field-type:"varchar" field-comment:"用户名称"`                                              // 用户名称
	UserType           string `gorm:"column:user_type;type:VARCHAR(10)" json:"user_type,omitempty" yaml:"user_type,omitempty" field-id:"user_type" field-type:"varchar" field-comment:"用户类型"`                                              // 用户类型
	EnName             string `gorm:"column:en_name;type:VARCHAR(64)" json:"en_name,omitempty" yaml:"en_name,omitempty" field-id:"en_name" field-type:"varchar" field-comment:"英文名称"`                                                      // 英文名称
	Passwd             string `gorm:"column:passwd;type:VARCHAR(64)" json:"passwd,omitempty" yaml:"passwd,omitempty" field-id:"passwd" field-type:"varchar" field-comment:"密码"`                                                            // 密码
	PasswdPower        string `gorm:"column:passwd_power;type:VARCHAR(64)" json:"passwd_power,omitempty" yaml:"passwd_power,omitempty" field-id:"passwd_power" field-type:"varchar" field-comment:"密码强度"`                                  // 密码强度
	NikeName           string `gorm:"column:nike_name;type:VARCHAR(64)" json:"nike_name,omitempty" yaml:"nike_name,omitempty" field-id:"nike_name" field-type:"varchar" field-comment:"昵称"`                                                // 昵称
	Gender             string `gorm:"column:gender;type:VARCHAR(10)" json:"gender,omitempty" yaml:"gender,omitempty" field-id:"gender" field-type:"varchar" field-comment:"性别"`                                                            // 性别
	Email              string `gorm:"column:email;type:VARCHAR(64)" json:"email,omitempty" yaml:"email,omitempty" field-id:"email" field-type:"varchar" field-comment:"邮箱"`                                                                // 邮箱
	Mobile             string `gorm:"column:mobile;type:VARCHAR(20)" json:"mobile,omitempty" yaml:"mobile,omitempty" field-id:"mobile" field-type:"varchar" field-comment:"手机号"`                                                           // 手机号
	Tel                string `gorm:"column:tel;type:VARCHAR(20)" json:"tel,omitempty" yaml:"tel,omitempty" field-id:"tel" field-type:"varchar" field-comment:"电话号"`                                                                       // 电话号
	Title              string `gorm:"column:title;type:VARCHAR(64)" json:"title,omitempty" yaml:"title,omitempty" field-id:"title" field-type:"varchar" field-comment:"头衔"`                                                                // 头衔
	DeptNo             string `gorm:"column:dept_no;type:VARCHAR(64)" json:"dept_no,omitempty" yaml:"dept_no,omitempty" field-id:"dept_no" field-type:"varchar" field-comment:"部门"`                                                        // 部门
	Avatar             string `gorm:"column:avatar;type:VARCHAR(300)" json:"avatar,omitempty" yaml:"avatar,omitempty" field-id:"avatar" field-type:"varchar" field-comment:"头像"`                                                           // 头像
	Addr               string `gorm:"column:addr;type:VARCHAR(64)" json:"addr,omitempty" yaml:"addr,omitempty" field-id:"addr" field-type:"varchar" field-comment:"地址"`                                                                    // 地址
	Position           string `gorm:"column:position;type:VARCHAR(64)" json:"position,omitempty" yaml:"position,omitempty" field-id:"position" field-type:"varchar" field-comment:"职位"`                                                    // 职位
	StaffNo            string `gorm:"column:staff_no;type:VARCHAR(10)" json:"staff_no,omitempty" yaml:"staff_no,omitempty" field-id:"staff_no" field-type:"varchar" field-comment:"员工编号"`                                                  // 员工编号
	Status             string `gorm:"column:status;type:VARCHAR(10)" json:"status,omitempty" yaml:"status,omitempty" field-id:"status" field-type:"varchar" field-comment:"状态"`                                                            // 状态
	UserStatus         string `gorm:"column:user_status;type:VARCHAR(10)" json:"user_status,omitempty" yaml:"user_status,omitempty" field-id:"user_status" field-type:"varchar" field-comment:"员工是否在职"`                                    // 员工是否在职
	UserGid            string `gorm:"column:user_gid;type:VARCHAR(64)" json:"user_gid,omitempty" yaml:"user_gid,omitempty" field-id:"user_gid" field-type:"varchar" field-comment:"用户全局ID"`                                                // 用户全局ID
	Education          string `gorm:"column:education;type:VARCHAR(64)" json:"education,omitempty" yaml:"education,omitempty" field-id:"education" field-type:"varchar" field-comment:"学历"`                                                // 学历
	School             string `gorm:"column:school;type:VARCHAR(300)" json:"school,omitempty" yaml:"school,omitempty" field-id:"school" field-type:"varchar" field-comment:"毕业学校"`                                                         // 毕业学校
	AdmissionDate      string `gorm:"column:admission_date;type:VARCHAR(10)" json:"admission_date,omitempty" yaml:"admission_date,omitempty" field-id:"admission_date" field-type:"varchar" field-comment:"毕业日期"`                          // 毕业日期
	MemberStatus       string `gorm:"column:member_status;type:VARCHAR(10)" json:"member_status,omitempty" yaml:"member_status,omitempty" field-id:"member_status" field-type:"varchar" field-comment:"在线状态 1 在线，2 闲置，3 勿扰，4 隐身 (默认1 在线)"` // 在线状态 1 在线，2 闲置，3 勿扰，4 隐身 (默认1 在线)
	Background         string `gorm:"column:background;type:VARCHAR(255)" json:"background,omitempty" yaml:"background,omitempty" field-id:"background" field-type:"varchar" field-comment:"背景色"`                                          // 背景色
	Backbanner         string `gorm:"column:backbanner;type:VARCHAR(255)" json:"backbanner,omitempty" yaml:"backbanner,omitempty" field-id:"backbanner" field-type:"varchar" field-comment:"横幅"`                                           // 横幅
	DecorationAvatorId string `gorm:"column:decoration_avator_id;type:VARCHAR(64)" json:"decoration_avator_id,omitempty" yaml:"decoration_avator_id,omitempty" field-id:"decoration_avator_id" field-type:"varchar" field-comment:"装饰头像"`  // 装饰头像
	ProfileEffectsId   string `gorm:"column:profile_effects_id;type:VARCHAR(64)" json:"profile_effects_id,omitempty" yaml:"profile_effects_id,omitempty" field-id:"profile_effects_id" field-type:"varchar" field-comment:"个人资料效果"`        // 个人资料效果
	MainTheme          string `gorm:"column:main_theme;type:VARCHAR(255)" json:"main_theme,omitempty" yaml:"main_theme,omitempty" field-id:"main_theme" field-type:"varchar" field-comment:"主色调"`                                          // 主色调
	MinorTheme         string `gorm:"column:minor_theme;type:VARCHAR(255)" json:"minor_theme,omitempty" yaml:"minor_theme,omitempty" field-id:"minor_theme" field-type:"varchar" field-comment:"颜色选择器"`                                    // 颜色选择器
	NameColor          string `gorm:"column:name_color;type:VARCHAR(64)" json:"name_color,omitempty" yaml:"name_color,omitempty" field-id:"name_color" field-type:"varchar" field-comment:"名字颜色"`                                          // 名字颜色
	FrameType          string `gorm:"column:frame_type;type:VARCHAR(255)" json:"frame_type,omitempty" yaml:"frame_type,omitempty" field-id:"frame_type" field-type:"varchar" field-comment:"边框"`                                           // 边框
	Birthday           string `gorm:"column:birthday;type:VARCHAR(64)" json:"birthday,omitempty" yaml:"birthday,omitempty" field-id:"birthday" field-type:"varchar" field-comment:"生日"`                                                    // 生日
	Major              string `gorm:"column:major;type:VARCHAR(255)" json:"major,omitempty" yaml:"major,omitempty" field-id:"major" field-type:"varchar" field-comment:"专业"`                                                               // 专业
	Degree             string `gorm:"column:degree;type:VARCHAR(64)" json:"degree,omitempty" yaml:"degree,omitempty" field-id:"degree" field-type:"varchar" field-comment:"学位"`                                                            // 学位
	Hoppy              string `gorm:"column:hoppy;type:VARCHAR(255)" json:"hoppy,omitempty" yaml:"hoppy,omitempty" field-id:"hoppy" field-type:"varchar" field-comment:"爱好"`                                                               // 爱好
	SocialAccounts     string `gorm:"column:social_accounts;type:VARCHAR(255)" json:"social_accounts,omitempty" yaml:"social_accounts,omitempty" field-id:"social_accounts" field-type:"varchar" field-comment:"社交账号"`                     // 社交账号
	PerIntroduction    string `gorm:"column:per_introduction;type:VARCHAR(255)" json:"per_introduction,omitempty" yaml:"per_introduction,omitempty" field-id:"per_introduction" field-type:"varchar" field-comment:"个人介绍"`                 // 个人介绍
	WorkDate           string `gorm:"column:work_date;type:VARCHAR(10)" json:"work_date,omitempty" yaml:"work_date,omitempty" field-id:"work_date" field-type:"varchar" field-comment:"参加工作日期"`                                            // 参加工作日期
	Language           string `gorm:"column:language;type:VARCHAR(64)" json:"language,omitempty" yaml:"language,omitempty" field-id:"language" field-type:"varchar" field-comment:"语言"`                                                    // 语言
	Area               string `gorm:"column:area;type:VARCHAR(64)" json:"area,omitempty" yaml:"area,omitempty" field-id:"area" field-type:"varchar" field-comment:"地区"`                                                                    // 地区
	Timeformat         string `gorm:"column:timeformat;type:VARCHAR(64)" json:"timeformat,omitempty" yaml:"timeformat,omitempty" field-id:"timeformat" field-type:"varchar" field-comment:"时间格式"`                                          // 时间格式
	Datefromat         string `gorm:"column:datefromat;type:VARCHAR(64)" json:"datefromat,omitempty" yaml:"datefromat,omitempty" field-id:"datefromat" field-type:"varchar" field-comment:"日期格式"`                                          // 日期格式
	WorkStatus         string `gorm:"column:work_status;type:VARCHAR(10)" json:"work_status,omitempty" yaml:"work_status,omitempty" field-id:"work_status" field-type:"varchar" field-comment:"工作状态"`                                      // 工作状态
	WorkSign           string `gorm:"column:work_sign;type:VARCHAR(255)" json:"work_sign,omitempty" yaml:"work_sign,omitempty" field-id:"work_sign" field-type:"varchar" field-comment:"工作签名"`                                             // 工作签名
	WorkSignicon       string `gorm:"column:work_signicon;type:VARCHAR(255)" json:"work_signicon,omitempty" yaml:"work_signicon,omitempty" field-id:"work_signicon" field-type:"varchar" field-comment:"工作签名的icon"`                        // 工作签名的icon
	Duty               string `gorm:"column:duty;type:VARCHAR(255)" json:"duty,omitempty" yaml:"duty,omitempty" field-id:"duty" field-type:"varchar" field-comment:"职务"`                                                                   // 职务
	JoinedDate         string `gorm:"column:joined_date;type:VARCHAR(10)" json:"joined_date,omitempty" yaml:"joined_date,omitempty" field-id:"joined_date" field-type:"varchar" field-comment:"入职日期"`                                      // 入职日期
	LeaveDate          string `gorm:"column:leave_date;type:VARCHAR(10)" json:"leave_date,omitempty" yaml:"leave_date,omitempty" field-id:"leave_date" field-type:"varchar" field-comment:"离职日期"`                                          // 离职日期
	DataCrtDate        string `gorm:"column:data_crt_date;type:VARCHAR(10)" json:"data_crt_date,omitempty" yaml:"data_crt_date,omitempty" field-id:"data_crt_date" field-type:"varchar" field-comment:"创建日期"`                              // 创建日期
	DataCrtTime        string `gorm:"column:data_crt_time;type:VARCHAR(20)" json:"data_crt_time,omitempty" yaml:"data_crt_time,omitempty" field-id:"data_crt_time" field-type:"varchar" field-comment:"创建时间"`                              // 创建时间
	DataUpdDate        string `gorm:"column:data_upd_date;type:VARCHAR(10)" json:"data_upd_date,omitempty" yaml:"data_upd_date,omitempty" field-id:"data_upd_date" field-type:"varchar" field-comment:"更新日期"`                              // 更新日期
	DataUpdTime        string `gorm:"column:data_upd_time;type:VARCHAR(20)" json:"data_upd_time,omitempty" yaml:"data_upd_time,omitempty" field-id:"data_upd_time" field-type:"varchar" field-comment:"更新时间"`                              // 更新时间
}

func (IdmUser) TableName() string { return "idm_user" }
